Part-2/Chapter-9/SportsSln/SportsStore/Components/CartInfoViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;

namespace SportsStore.Components
{
    public class CartInfoViewComponent : ViewComponent
    {
        public Cart Cart;
        public CartInfoViewComponent(Cart cartService) 
        {
            Cart = cartService;
        }

        public IViewComponentResult Invoke()
        {
            return View(Cart);
        }
    }
}

Part-2/Chapter-9/SportsSln/SportsStore/Components/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;

namespace SportsStore.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private IStoreRepository Repo;
        public NavigationMenuViewComponent(IStoreRepository repository) 
        {
            Repo = repository;
        }
        public IViewComponentResult Invoke() 
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];
            return View(Repo.Products.Select(p=>p.Category).Distinct().OrderBy(p=>p));
        }
    }
}

Part-2/Chapter-9/SportsSln/SportsStore/Pages/Cart.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SportsStore.Models;
using SportsStore.Infrastructure;

namespace SportsStore.Pages
{
    public class CartModel : PageModel
    {
        private IStoreRepository Repository;
        public CartModel(IStoreRepository repository , Cart cartService) 
        {
            Repository = repository;
            Cart = cartService;
        }

        public Cart Cart { get; set; }
        public string? UrlPath { get; set; } = string.Empty;
        public void OnGet(string urlPath)
        {
            UrlPath = urlPath ?? "/";
        }


        public IActionResult OnPostAdd(int ProductID , string urlPath) 
        {
            //getting the product
            var p = Repository.Products.Where(p => p.ProductID == ProductID).FirstOrDefault();
            
            if (p is not null) 
            {
                //add to the cart
                /*Cart cart_temp = HttpContext.Session.GetJson<Cart>("cart") ?? new();
                cart_temp.AddItem(p);
                HttpContext.Session.SetJson("cart", cart_temp);*/
                Cart.AddItem(p, 1);
            }

            return RedirectToPage(new { urlPath = urlPath});
        }

        public IActionResult OnPostRemove(int ProductID , string urlPath) 
        {
            Cart.RemoveItem(ProductID);
            return RedirectToPage(new { urlPath = urlPath});
        }
    }
}

Part-2/Chapter-9/SportsSln/SportsStore/Views/Shared/ProductSummary.cshtml
@model Product
@using SportsStore.Components

<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4>
            @Model.Name
            <span class="badge rounded-pill bg-primary text-white"
                  style="float:right">
                <small>@Model.Price.ToString("c")</small>
            </span>
        </h4>
    </div>

        <span class="card-text p-1">
            @Model.Description
            <form method="post" asp-page="/Cart" asp-page-handler="Add">
                <input type="hidden" value="@Model.ProductID" name="ProductID" />
                <input type="hidden" 
                        name="urlPath"
                   value="@ViewContext.HttpContext.Request.PathAndQuery()" />
                <button style ="float: right "type="submit" class="btn btn-success">Add To Cart</button>
            </form>
        </span>
    

</div>

Part-2/Chapter-9/SportsSln/SportsStore/Views/Shared/_Layout.cshtml

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SportsStore</title>
    <link href="/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/lib/fontawesome/css/all.min.css" rel="stylesheet" />
</head>
<body>
    <div class="bg-dark text-white p-2">
        <div class="row">
            <div class="col navbar-brand">
                Sports Store
            </div>
            <div class="col-6 navbar-text text-end">

                <vc:cart-info />
            </div>
        </div>
    </div>
    <div class="row m-1 p-1">
        <div id="categories" class="col-3">
            <vc:navigation-menu/>
        </div>
        <div class="col-9">
            @RenderBody()
        </div>
    </div>
</body>
</html>